language: node_js
node_js:
  - "0.12"

script: grunt

before_install:
  - npm install -g grunt-cli
  - gem install scss-lint
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

notifications:
  slack: 
	rooms:
	 - kickstart-dec15:tS0aWyPZ1kYU4cTtx42ZrBn7
	on_success: never
	on_failure: always
